branches:
  only:
  - develop
  - master
language: ruby
rvm:
- 2.6.7
before_script:
- chmod +x ci.sh
script: ./ci.sh
env:
  global:
    secure: UwZfR1zlq+42af+6PACVJ+e9qcaHo2ibXiEbFQHQXkCj9cG0DLmdJ6LrhZ9WO0Za/HlB5Lv9988xWV/VGkH10K3n1e59xzEggDYCLpaR3L+YsPHbvX6q9GHKowePo+eztmwI5Vx65zHMMM+9G2mwzzyQBt3yOIG/k90+dUbGtPs=
