basic_auth:
  username: admin
  password: password

catalog:
  services: # catalog must advertise at least one service
    - id: 5085f1cb-e093-4630-8795-843b76018eb8
      name: github-repo
      description: Provides read and write access to a GitHub repository.
      bindable: true
      tags:
        - github
      plans: # a service has one or more plans
        - id: c05855e7-a55d-4ba1-b462-7579df7514f4
          name: public
          description: All repositories are public

github:
  username: #<your-github-username>
  access_token: #<token-value>
  # The access token is used in place of username/password to access your GitHub account.
  # To generate the access token, run the following command,
  # then copy the value from the "token" field in the response:
  # curl -u <your-github-username> -d '{"scopes": ["repo", "delete_repo"], "note": "my fancy token"}' https://api.github.com/authorizations